Fix seg fault on marble activation
edgelesssys/marblerun pull request #124
Opened 2021-03-25 16:25 UTC by daniel-weisse

There was an error where a segmentation fault occurred when a marble sent an activation request to the coordinator but the "Parameters" field in the Marblerun manifest was left empty. 
The coordinator would then try reading a value from a nil pointer and crash
This fixes that error by setting the Parameters field to default values if it was not provided by the Manifest (same as if the Manifest had specified '"Parameters": {}')

2021-03-25 16:33 UTC, m1ghtym0 approved these changes

2021-03-25 16:40 UTC, thomasten requested changes

2021-03-25 16:40 UTC, thomasten commented on coordinator/manifest/manifest.go
> +		if marble.Parameters == nil {
Unit test is missing. In general, write a unit test and make sure it fails before fixing a bug. (See our workflow.)

2021-03-27 14:20 UTC, thomasten approved these changes
thanks!

2021-03-27 14:20 UTC, merged