Feat/redis demo
edgelesssys/marblerun pull request #127
Opened 2021-04-06 07:12 UTC by m1ghtym0

2021-04-06 07:19 UTC, daniel-weisse commented on samples/graphene-redis/README.md
> +* Install Marblerun on the Clutser
```suggestion
* Install Marblerun on the Clutser
```
* Install Marblerun on the Cluster

2021-04-06 07:24 UTC, daniel-weisse commented on samples/graphene-redis/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
This file can be removed now

2021-04-06 08:04 UTC, daniel-weisse approved these changes

2021-04-06 09:14 UTC, thomasten requested changes

2021-04-06 09:14 UTC, thomasten commented on samples/graphene-redis/README.md
> +The current Dockerfile is poorly optimized and can probably be configured to be smaller and more efficient, but for the sake of this demo it works
Can we rephrase it to sound a bit nicer?

2021-04-07 08:01 UTC, m1ghtym0 commented on samples/graphene-redis/README.md
> +First, ensure you have access to a Kubernetes cluster with SGX-enabled nodes and kubectl installed and configured.
Not sure, can Graphene run in simulation mode, or does it require rebuilding?

2021-04-07 08:12 UTC, thomasten commented on samples/graphene-redis/README.md
> +First, ensure you have access to a Kubernetes cluster with SGX-enabled nodes and kubectl installed and configured.
Don't know. Let's just keep it as is and don't waste time trying.

2021-04-07 08:14 UTC, thomasten requested changes

2021-04-07 08:14 UTC, thomasten commented on samples/graphene-redis/README.md
> +Assuming you have built Graphene in `/graphene` copy the redis-server.manifest.template into the `/graphene/Examples/redis`
```suggestion
To marbleize the sample we edited [redis-server.manifest.template](redis-server.manifest.template). See comments starting with `MARBLERUN` for explanations of the required changes.

Assuming you have built Graphene in `/graphene` copy the redis-server.manifest.template into the `/graphene/Examples/redis`
```
suggest new paragraph

2021-04-07 08:14 UTC, thomasten commented on samples/graphene-redis/README.md
> +To marbleize the sample we edited [redis-server.manifest.template](redis-server.manifest.template). See comments starting with `MARBLERUN` for explanations of the required changes.
```suggestion
To marbleize the sample we edited [redis-server.manifest.template](redis-server.manifest.template).
```
either remove the sentence or add these comments

2021-04-07 08:29 UTC, thomasten approved these changes

2021-04-07 08:40 UTC, merged