AB#757 Load correct era-config depending on coordinator version
edgelesssys/marblerun pull request #128
Opened 2021-04-06 09:09 UTC by daniel-weisse

Instead of always loading the latest era-config, we now check what version the coordinator is running and try to download a matching config

2021-04-06 09:17 UTC, m1ghtym0 approved these changes

2021-04-07 08:07 UTC, m1ghtym0 requested changes

2021-04-07 08:07 UTC, m1ghtym0 commented on cli/cmd/util.go
> +	eraURL := fmt.Sprintf("https://github.com/edgelesssys/marblerun/releases/%s/download/coordinator-era.json", coordinatorVersion)
```suggestion
	eraURL := fmt.Sprintf("https://github.com/edgelesssys/marblerun/releases/download/%s/coordinator-era.json", coordinatorVersion)
```
Seems that the URL for a specific version is https://github.com/edgelesssys/marblerun/releases/download/v0.3.0/coordinator-era.json
While for latest there is a shortcut:
https://github.com/edgelesssys/marblerun/releases/latest/download/coordinator-era.json

2021-04-07 08:40 UTC, m1ghtym0 approved these changes

2021-04-08 06:30 UTC, merged

2021-04-12 08:10 UTC, Nirusu commented on cli/cmd/util.go
> +	resp, err := http.Get(eraURL)
I know this has already been merged, but still: Maybe add an error check for non-HTTP 200 here if we dynamically construct the URL?