AB#993 CLI secret get/set
edgelesssys/marblerun pull request #193
Opened 2021-06-18 10:46 UTC by daniel-weisse

### Proposed changes
- Add a command to retrieve secrets from the coordinator using the API endpoint from https://github.com/edgelesssys/marblerun/pull/188
  - supports saving to file as json or printing to stdout in readable format
- Add a command to set secrets for the coordinator using the API endpoint from https://github.com/edgelesssys/marblerun/pull/191
  - requires a json file defining the secrets as described in the original PR

### Additional info
Also updates the `restClient` function to accept an optional client tls certificate to create a http client with user certificate

2021-06-18 11:21 UTC, m1ghtym0 requested changes
Please add a follow-up ticket for setting secrets from pem files directly.

2021-06-18 11:21 UTC, m1ghtym0 commented on cli/cmd/secret.go
> +Used to either set a secret, or retrieve a secret used by the coordinator.`,
```suggestion
Manages secrets for the Marblerun coordinator.
Set or retrieve a secret defined in the manifest.`,
```

2021-06-18 11:21 UTC, m1ghtym0 commented on cli/cmd/secretGet.go
> +and has to be permitted to read the requested secrets.
```suggestion
Users have to authenticate themselves using a certificate and private key,
and need permissions in the manifest to read the requested secrets.
```

2021-06-18 11:21 UTC, m1ghtym0 commented on cli/cmd/secretGet.go
> +	url := url.URL{Scheme: "https", Host: o.host, Path: "secrets", RawQuery: secretQuery}
```suggestion
	secretQuery := url.Values{}
	for _, secret := range o.secretIDs {
		secertQuery.Add("s", secert)
	}
	url := url.URL{Scheme: "https", Host: o.host, Path: "secrets", RawQuery: secretQuery.Encode()}
```

2021-06-18 11:21 UTC, m1ghtym0 commented on cli/cmd/secretSet.go
> +and has to be permitted to write the requested secrets.
```suggestion
Set a secret for the Marblerun coordinator.
Users have to authenticate themselves using a certificate and private key
and need permissions in the manifest to write the requested secrets.
```

2021-06-23 11:03 UTC, m1ghtym0 requested changes

2021-06-23 11:06 UTC, daniel-weisse commented on cli/cmd/secretSet.go
> +	cmd.Flags().StringVar(&pemFile, "from-pem", "", "set to load a secret from a PEM encoded file")
Looking at it again this seems to be a lot better actually.
Make it `marblerun secret set foo.pem --from-pem foo`

2021-06-23 13:36 UTC, m1ghtym0 requested changes

2021-06-23 13:36 UTC, m1ghtym0 commented on cli/cmd/secretGet.go
> +			return fmt.Errorf("Did not receive the same number of secrets as requested")
```suggestion
			return fmt.Errorf("did not receive the same number of secrets as requested")
```

2021-06-23 13:45 UTC, m1ghtym0 approved these changes

2021-06-23 13:58 UTC, merged