Minor fixups of client API documentation
edgelesssys/marblerun pull request #241
Opened 2021-08-20 09:38 UTC by katexochen

Porting edgelesssys/docs.edgeless.systems#21 to this repository, since API documentation is done alongside with code in this repository since #234.

2021-08-31 12:53 UTC, m1ghtym0 requested changes

2021-08-31 13:00 UTC, m1ghtym0 approved these changes

2021-09-01 09:13 UTC, leongross reviewed
lgtm

2021-09-01 09:15 UTC, leongross approved these changes

2021-09-01 09:34 UTC, daniel-weisse commented on coordinator/server/client_api.go
> +// Each request allows specifying one or more secrets in the form of a query string, where each parameter `s` specifies one secret.
The request type is specified in the swagger specs (line 294 for `secrets` shows this is a GET request).
[Rendered in the docs](https://docs.edgeless.systems/marblerun/#/reference/coordinator) it is very clear what type of request one is dealing with

2021-09-07 08:21 UTC, merged