implement a log of events queriable from the metrics endpoint
edgelesssys/marblerun pull request #306
Opened 2022-07-13 13:11 UTC by aep

fixes #304

2022-07-14 06:16 UTC, m1ghtym0 approved these changes
lgtm:-)

2022-07-14 06:49 UTC, daniel-weisse requested changes

2022-07-14 06:49 UTC, daniel-weisse commented on coordinator/events/eventlog.go
> +//
Please run `gofmt -w coordinator/events/eventlog.go` to format this file.

Also all top-level, exported types and functions should have doc comments.

2022-07-14 06:49 UTC, daniel-weisse commented on coordinator/core/core.go
> +func NewCore(dnsNames []string, qv quote.Validator, qi quote.Issuer, sealer seal.Sealer, recovery recovery.Recovery, zapLogger *zap.Logger, promFactory *promauto.Factory, eventlog *events.Log) (*Core
Unit tests that call `NewCore()` need to be update.

2022-07-14 06:49 UTC, daniel-weisse commented on coordinator/events/eventlog.go
> +}
```suggestion
func (l *Log) Activation(marbleType string, uuid string, quote []byte) {
	l.events = append(l.events, Event{
		Timestamp:	time.Now(),
		Activation: &ActivationEvent{MarbleType: marbleType, UUID: uuid, Quote: quote},
	})
}

func (l *Log) Handler() http.HandlerFunc {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		json.NewEncoder(w).Encode(l.events)
	})
}
```
Just a small style nitpick

2022-07-15 06:13 UTC, daniel-weisse commented on coordinator/events/eventlog.go
> +func (l *Log) Handler() http.HandlerFunc {
```suggestion
// Handler returns a http.HandlerFunc which writes the log as JSON array.
func (l *Log) Handler() http.HandlerFunc {
```

2022-07-15 06:36 UTC, daniel-weisse approved these changes

2022-07-15 06:37 UTC, merged