RFC: emit cert as Java KeyStore
edgelesssys/marblerun pull request #309
Opened 2022-07-21 13:17 UTC by aep

see #307

turns out jks is slightly more annoying because it is usually used in a multi-step process of adding certs into a store,
but we need to emit the file in one go, merging all the inputs.

so the proposed semantic is

```json
"/app/keystore.jks": "{{ javaKeyStore \"password\" \"alias\"  .MarbleRun.MarbleCert.Private .MarbleRun.MarbleCert.Cert }}", 
"/app/trustme.jks": "{{ javaKeyStore \"password\" \"alias\"  nil .MarbleRun.MarbleCert.Cert }}", 

```

2022-07-21 13:46 UTC, m1ghtym0 commented
Let me clarify because I'm not that familiar with JKS.
The JKS only holds keys or certificates or can it store arbitrary binary blobs?
In case we only speak about keys&certs, IMO we can assume that these can always be represented using `manifest.Secret`.
That can include constants or Coordinator generated values.

2022-07-21 13:53 UTC, aep commented
> The JKS only holds keys or certificates or can it store arbitrary binary blobs?

The only relevant use case is to store certificates to use as trust root, and for storing private keys for a cert.

> In case we only speak about keys&certs, IMO we can assume that these can always be represented using manifest.Secret.

yeah i agree. i'm going to make it do that. i was just wondering if there's use cases in marblerun that i'm not seing. but since you can load pretty much everything into a manifest.Secret it should be fine.

2022-07-21 14:47 UTC, daniel-weisse requested changes
Thanks, looks good to me.
Just a couple of style things

2022-07-21 14:47 UTC, daniel-weisse commented on .dockerignore
> +Dockerfile
```suggestion
```

2022-07-21 14:47 UTC, daniel-weisse commented on coordinator/manifest/manifest.go
> +	var ks = keystore.New()
```suggestion
	ks := keystore.New()
```

2022-07-21 14:47 UTC, daniel-weisse commented on coordinator/manifest/manifest.go
> +func EncodeSecretsToJavaKeyStore(password string, secrets...Secret) (string, error) {
```suggestion
// EncodeSecretsToJavaKeyStore encodes secrets as java keystore.
func EncodeSecretsToJavaKeyStore(password string, secrets ...Secret) (string, error) {
```

2022-07-21 14:47 UTC, aep commented
done. let me know about additional changes.

the test only checks if the semantics work, it doesnt actually test if the keystore is valid.
i feel like that would drag in too much java stuff.

2022-07-21 15:30 UTC, aep commented
uuuh it turns out there might be a use case where you dont want to important the entire secret

specifically edb.

the service that connects to edb should NOT have the secret

2022-08-10 07:15 UTC, m1ghtym0 commented
Hey @aep,

> I like the latter option better. You can pass `edbSecret.Cert` to the client Marble and `edbSecret` to edb. The handler function just handles both cases.

Does that sound good to you?

2022-11-02 16:01 UTC, aep commented
oh hey sorry about this. my customer hasn't really focused on this.
i think the best course of action is to keep the patch downstream.

2022-11-02 16:01 UTC, closed without merging