AB#363 Generate certificates as secret
edgelesssys/marblerun pull request #73
Opened 2020-11-30 15:30 UTC by Nirusu

This PR adds support to define a certificate as secret which should be generated.

This can be done by following the x509.Certificate golang object notation. Every field from the object can be defined in the manifest, the generator will take most values and overwrite some of them and generate a key pair + certificate based on them.

Right now, this is not completely done yet as tests are failing, documentation still needs to be provided etc., but it should be ready for review.

2020-12-01 12:52 UTC, Nirusu commented
Tests are now passing with the latest change to get rid of the pointer in the struct. Might be worth to check if there are still some good test cases I could add, this feature feels really fragile to work on.

2020-12-01 14:55 UTC, thomasten requested changes

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/core.go
> +func (c *Core) generateCertificateForSecret(secret Secret, key interface{}) (x509.Certificate, error) {
```suggestion
func (c *Core) generateCertificateForSecret(secret Secret, key crypto.PublicKey) (x509.Certificate, error) {
```

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/core.go
> +	var template *x509.Certificate
```suggestion
	var template x509.Certificate
```

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/core.go
> +		template.IPAddresses = c.cert.IPAddresses
```suggestion
		template.IPAddresses = util.DefaultCertificateIPAddresses
```
and add `var DefaultCertificateIPAddresses = []net.IP{net.IPv4(127, 0, 0, 1), net.IPv6loopback}` to util/tls.go and also replace all other occurrences

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/core.go
> +		template.DNSNames = c.cert.DNSNames
```suggestion
		template.DNSNames = []string{"localhost"}
```

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/core.go
> +		template.SerialNumber, err = rand.Int(rand.Reader, big.NewInt(999999999999999999))
```suggestion
		template.SerialNumber, err = util.GenerateCertificateSerialNumber()
```

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/core.go
> +	}
```suggestion
	if secret.ValidFor == 0 {
		secret.ValidFor = 365
	}
	template.NotAfter = time.Now().Add(time.Hour * 24 * time.Duration(secret.ValidFor))
```

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/core_test.go
> +	assert.IsType(x509.Certificate{}, generatedSecrets["cert-ecdsa-test"].Cert)
These are always true. Instead, check some fields of the certificates.

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/marbleapi_test.go
> +		ms.assert.NotNil(p)
```suggestion
```

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/marbleapi_test.go
> +	}
Check that NotAfter-NotBefore is 7 days

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/marbleapi_test.go
> +	key, err := rsa.GenerateKey(rand.Reader, int(2048))
```suggestion
	key, err := rsa.GenerateKey(rand.Reader, 2048)
```

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/marbleapi_test.go
> +	}
```suggestion
	require.NoError(err)
```

2020-12-01 14:55 UTC, thomasten commented on coordinator/core/marbleapi_test.go
> +	assert.NotNil(p)
```suggestion
	require.NotNil(p)
```

2020-12-06 17:10 UTC, thomasten requested changes

2020-12-06 17:10 UTC, thomasten commented on coordinator/core/core.go
> +	if err != nil {
```suggestion
	// Generate certificate with given public key
	secretCertRaw, err := x509.CreateCertificate(rand.Reader, &template, c.cert, pubKey, c.privk)
	if err != nil {
```

2020-12-06 17:10 UTC, thomasten commented on coordinator/core/marbleapi_test.go
> +	parsedSecret, err = parseSecrets("{{ pem .Secrets.testcertificate.Cert }}", testWrappedSecrets)
also add a test for `{{ raw .Secrets.testcertificate.Cert }}` (and implement the feature)

2020-12-07 08:29 UTC, Nirusu commented on test/manifests.go
> +			"ValidFor": 7
Not really sure about this one. This creates ambiguity with the x509.Certificate fields (ValidFor vs. NotAfter), plus directly addressing or setting the certificate as an object becomes uglier.

2020-12-07 09:57 UTC, thomasten requested changes

2020-12-07 09:57 UTC, thomasten commented on coordinator/core/manifest.go
> +	if cert, ok := data.(x509.Certificate); ok {
we should also use a switch here

2020-12-07 09:57 UTC, thomasten commented on coordinator/core/core.go
> +	} else if !template.NotAfter.IsZero() && secret.ValidFor != 0 {
```suggestion
	} else if secret.ValidFor != 0 {
```

2020-12-07 13:47 UTC, m1ghtym0 approved these changes
LGTM:-)
We should make a new release with this one.
I've seen the docs already get updated👍

2020-12-07 13:53 UTC, Nirusu commented
I'd suggest we wait for a new release until the "unique"/"marble only" secrets are merged, then this feels more complete, I guess.

I'll open the PR for it right when this one is merged into master, maybe we can get everything done related to secrets this week :)

2020-12-07 14:29 UTC, m1ghtym0 commented
> I'd suggest we wait for a new release until the "unique"/"marble only" secrets are merged, then this feels more complete, I guess.
> 
> I'll open the PR for it right when this one is merged into master, maybe we can get everything done related to secrets this week :)

Oh, wasn't aware there is more open work in secrets. Sure let's wait until secrets is complete.

2020-12-07 15:33 UTC, thomasten approved these changes

2020-12-07 15:33 UTC, merged