Allow specifying accepted avisories for `SWHardeningNeeded` TCB status
edgelesssys/marblerun pull request #733
Opened 2024-09-26 12:58 UTC by daniel-weisse

https://github.com/edgelesssys/marblerun/pull/729 added support for reading the Security Advisories if attestation failed due to invalid TCB status.
This PR builds on that to allow users to specify just specific advisories when the reported TCB status is `SWHardeningNeeded`

### Proposed changes
- Add a new flag to the CLI `--accepted-advisories` which allows specifying a list of Intel Security Advisories to accept if the Coordinator's TCB status is `SWHardeningNeeded`. If not set, all advisories are accepted
- Add a new manifest field `Packages.AcceptedAdvisories` which allows specifying a list of Intel Security Advisories to accept if the package's TCB status is `SWHardeningNeeded`. If not set, all advisories are accepted
- Fix for the CLI printing a `nil` error if parsing the advisory list of a report failed

2024-09-27 14:09 UTC, thomasten requested changes

2024-09-27 14:09 UTC, thomasten commented on coordinator/quote/ert.go
> +	AcceptedAdvisories []string
This must be copied in UpdateManifest in clientapi.go. This should also be covered by some test.

2024-09-27 14:09 UTC, thomasten commented on api/attestation/attestation_test.go
> +				config.AcceptedAdvisories = []string{"INTEL-SA-0002"}
```suggestion
				config.AcceptedTCBStatuses = []string{"SWHardeningNeeded"}
				config.AcceptedAdvisories = []string{"INTEL-SA-0002"}
```

2024-09-30 14:45 UTC, daniel-weisse commented on coordinator/quote/ertvalidator/ertvalidator.go
> +		return fmt.Errorf("TCB status %s contains advisories not accepted by configuration: %s", report.TCBStatus, notAccepted)
We log any failed Marble verification attempts in `coordinator/core/marbleapi.go`. That log statement contains the error returned by this package.
Is there any information missing you would prefer to be logged in `ertvalidator.go`?

2024-10-01 13:56 UTC, thomasten commented on coordinator/quote/ertvalidator/ertvalidator.go
> +		return fmt.Errorf("TCB status %s contains advisories not accepted by configuration: %s", report.TCBStatus, notAccepted)
I'm not sure, but I think I've seen log outputs of failed activations where we could have given more details. However, this is out of scope. I may revisit this myself at some point.

2024-10-01 13:56 UTC, thomasten approved these changes

2024-10-02 06:31 UTC, merged