AB#494 & AB#496 : Allow updating the required SecurityVersion of a package
edgelesssys/marblerun pull request #85
Opened 2021-01-12 16:42 UTC by Nirusu

Short summary of changes:

- New section `Admins` in manifest, allowing to specify **user-defined** certificates (which get saved to the core)
- Introduction of an 'update manifest', which allows to specify a new, higher SecurityLevel than set in the original manifest
- This 'update manifest' does not overwrite the original manifest, but is saved additionally in the core
- The update manifest can be set over the '/update' API endpoint, when one of the client certificates from `Admins` was used (and if none was set, this API endpoint stays locked)
- The certificates are **not fully verified**. We only check if the supplied one is equal to one of the defined ones in `Admins`, and Go's TLS stack should ensure that the user calling the API endpoint does own the private key to its own certificate. Expiration and trust anchors are not checked here, we basically just abuse TLS client certificates here for a public/private key check and do not care about the rest of the X.509 certificate stuff. Guess we need to check carefully here if this provides sufficient security.

2021-01-17 13:00 UTC, thomasten requested changes

2021-01-18 12:59 UTC, Nirusu commented on coordinator/core/manifest.go
> +type UpdateManifest struct {
We can, and I changed it in the last commit. I'll just use a different check function for the update case, and other values should automatically be ignored for now.

2021-01-18 15:38 UTC, thomasten requested changes

2021-01-18 15:38 UTC, thomasten commented on coordinator/core/clientapi.go
> +	adminCerts := make([]*x509.Certificate, len(manifest.Admins))
```suggestion
	adminCerts := make([]*x509.Certificate)
```
or
```suggestion
	adminCerts := make([]*x509.Certificate, 0, len(manifest.Admins))
```

2021-01-18 15:38 UTC, thomasten commented on coordinator/core/core.go
> +	// Parse & write X.509 admin certificates from sealed state
refactor into function and also use it in SetManifest

2021-01-18 15:38 UTC, thomasten commented on coordinator/core/core.go
> +	return cert, adminCerts, privk, err
I think we don't need to return adminCerts. Just create it before the other assignments above and then assign it with the others.

2021-01-18 15:38 UTC, thomasten commented on coordinator/core/manifest.go
> +		if *singlePackage.SecurityVersion < *originalPackages[packageName].SecurityVersion {
singlePackage.SecurityVersion might be nil
originalPackages[packageName] might not exist
originalPackages[packageName].SecurityVersion might be nil

2021-01-18 15:38 UTC, thomasten commented on coordinator/server/server_test.go
> +}
```suggestion
```

2021-01-18 21:58 UTC, thomasten requested changes

2021-01-18 21:58 UTC, thomasten commented on coordinator/core/manifest.go
> +		// Checks if we already have an update manifest set, if it does contain the package and if it does, if it actually holds a value for SecurityVersion (which should always be the case, but let's go s
Also make sure that the new update manifest contains all the packages of alreadyUpdatedPackages.

2021-01-19 11:15 UTC, thomasten reviewed
I think this is fine now. Pls clean up the commit history before we merge this (see workflow steps 5 and 6).

2021-01-19 11:15 UTC, thomasten commented on coordinator/core/manifest.go
> +		if alreadyUpdatedPackages != nil {
```suggestion
```
range nil is fine

2021-01-19 12:39 UTC, thomasten approved these changes

2021-01-19 12:40 UTC, merged