AB#377: Modularize recovery
edgelesssys/marblerun pull request #87
Opened 2021-01-25 11:45 UTC by Nirusu

This PR makes the recovery module interchangeable for upcoming features such as multi-party recovery.

Changes from the already reviewed internal version:

- recoveryMap is always loaded into the core, not just when an unsealing error occurs 
- GetRecoveryData() added (for when we need to reseal the state for an update manifest)
- Properly some other minor stuff to accompany changes from other changes to Marblerun while this was in development

Leftover issues:

- The integration test can fail badly across tests when one of the subfunctions fails, as they often invoke `require` but no defer functions are set in them as we want to return the cfgs and alive processes for the calling main function. This can cause the next test function to work with an unclean coordinator, causing further test failures due to an unexpected state.

Guess we need an idea on how to cleanup a failure in this subfunction in a way which is not totally ugly, so any ideas are appreciated here.

Apart from that, this is ready for a final review.

2021-01-25 15:24 UTC, thomasten requested changes
Thanks for the clean commits, much appreciated.

2021-01-25 15:24 UTC, thomasten commented on util/util.go
> +func XORBytes(a, b []byte) ([]byte, error) {
add the test

2021-01-25 15:24 UTC, thomasten commented on coordinator/core/clientapi.go
> +	// Retrieve current recovery data before we seal the state again
do this before setting `c.updateManifest` so that the state does not change on error

2021-01-25 15:24 UTC, thomasten commented on coordinator/core/clientapi.go
> +	return nil
```suggestion
	return c.sealState(currentRecoveryData)
```

2021-01-25 17:33 UTC, thomasten approved these changes

2021-01-26 07:52 UTC, m1ghtym0 submitted a review, later dismissed

2021-01-26 08:57 UTC, thomasten approved these changes

2021-01-26 08:57 UTC, merged